### ISSUE TITLE
Add option to have button be a regular toolbar button

### ISSUE THREAD

**Issue by Gitoffthelawn** [pepelsbey/contenteditable#2]
Thanks for the useful extension!

Can you add an option to have the button be a regular toolbar button?  That way, it can be placed in Firefox's overflow menu and not take up any screen real-estate when not being used.

**Comment by Gitoffthelawn** [comment]
I just got notified this was closed after 3 years, but no status is indicated.  What's the status?

**Comment by pepelsbey** [comment]
I assumed that it might not be relevant anymore. And I’m sorry for not responding back then.

But still, I don’t see how to enable this without making it too complicated. It would require adding a page with a single icon placement option. It’s a bit too much for an extension like this.

**Comment by Gitoffthelawn** [comment]
No problem for not responding back then.  Life often gets in the way of such things! :)

IIRC, I was just thinking of a regular browser toolbar button like many extensions have that would act as a toggle to turn contenteditable on/off.
